DELETE FROM `creature` WHERE `id`=23118;
INSERT INTO `creature` (`guid`,`id`,`map`,`spawnMask`,`phaseMask`,`modelid`,`equipment_id`,`position_x`,`position_y`,`position_z`,`orientation`,`spawntimesecs`,`spawndist`,`currentwaypoint`,`curhealth`,`curmana`,`DeathState`,`MovementType`,`npcflag`,`unit_flags`,`dynamicflags`) VALUES
(211012, 23118, 530, 1, 1, 0, 0, 2824.71, 7044.79, 369.877, -0.750491, 20, 0, 0, 42, 0, 0, 0, 0, 33554432, 0),
(211011, 23118, 530, 1, 1, 0, 0, 2786.61, 7036.28, 370.686, -2.04204, 20, 0, 0, 42, 0, 0, 0, 0, 33554432, 0),
(211010, 23118, 530, 1, 1, 0, 0, 2764.71, 7024.45, 370.203, 2.89725, 20, 0, 0, 42, 0, 0, 0, 0, 33554432, 0),
(211009, 23118, 530, 1, 1, 0, 0, 2824.71, 7044.79, 369.877, -0.750491, 20, 0, 0, 42, 0, 0, 0, 0, 33554432, 0);



DELETE FROM `creature_questrelation` WHERE `quest` = 11010;
DELETE FROM `gameobject_questrelation` WHERE `quest` = 11010;
UPDATE `item_template` SET `StartQuest`=0 WHERE `StartQuest` = 11010;
INSERT INTO `creature_questrelation` (`id`, `quest`) VALUES (23120, 11010);
UPDATE `creature_template` SET `npcflag`=`npcflag`|2 WHERE `entry` = 23120;
DELETE FROM `creature_involvedrelation` WHERE `quest` = 11010;
DELETE FROM `gameobject_involvedrelation` WHERE `quest` = 11010;
INSERT INTO `creature_involvedrelation` (`id`, `quest`) VALUES (23120, 11010);
UPDATE `creature_template` SET `npcflag`=`npcflag`|2 WHERE `entry`=23120;
REPLACE INTO `quest_template` (`entry`, `Method`, `ZoneOrSort`, `SkillOrClassMask`, `MinLevel`, `MaxLevel`, `QuestLevel`, `Type`, `RequiredRaces`, `RequiredSkillValue`, `RepObjectiveFaction`, `RepObjectiveValue`, `RepObjectiveFaction2`, `RepObjectiveValue2`, `RequiredMinRepFaction`, `RequiredMinRepValue`, `RequiredMaxRepFaction`, `RequiredMaxRepValue`, `SuggestedPlayers`, `LimitTime`, `QuestFlags`, `SpecialFlags`, `CharTitleId`, `PlayersSlain`, `BonusTalents`, `RewardArenaPoints`, `PrevQuestId`, `NextQuestId`, `ExclusiveGroup`, `NextQuestInChain`, `RewXPId`, `SrcItemId`, `SrcItemCount`, `SrcSpell`, `Title`, `Details`, `Objectives`, `OfferRewardText`, `RequestItemsText`, `EndText`, `CompletedText`, `ObjectiveText1`, `ObjectiveText2`, `ObjectiveText3`, `ObjectiveText4`, `ReqItemId1`, `ReqItemId2`, `ReqItemId3`, `ReqItemId4`, `ReqItemId5`, `ReqItemId6`, `ReqItemCount1`, `ReqItemCount2`, `ReqItemCount3`, `ReqItemCount4`, `ReqItemCount5`, `ReqItemCount6`, `ReqSourceId1`, `ReqSourceId2`, `ReqSourceId3`, `ReqSourceId4`, `ReqSourceCount1`, `ReqSourceCount2`, `ReqSourceCount3`, `ReqSourceCount4`, `ReqCreatureOrGOId1`, `ReqCreatureOrGOId2`, `ReqCreatureOrGOId3`, `ReqCreatureOrGOId4`, `ReqCreatureOrGOCount1`, `ReqCreatureOrGOCount2`, `ReqCreatureOrGOCount3`, `ReqCreatureOrGOCount4`, `ReqSpellCast1`, `ReqSpellCast2`, `ReqSpellCast3`, `ReqSpellCast4`, `RewChoiceItemId1`, `RewChoiceItemId2`, `RewChoiceItemId3`, `RewChoiceItemId4`, `RewChoiceItemId5`, `RewChoiceItemId6`, `RewChoiceItemCount1`, `RewChoiceItemCount2`, `RewChoiceItemCount3`, `RewChoiceItemCount4`, `RewChoiceItemCount5`, `RewChoiceItemCount6`, `RewItemId1`, `RewItemId2`, `RewItemId3`, `RewItemId4`, `RewItemCount1`, `RewItemCount2`, `RewItemCount3`, `RewItemCount4`, `RewRepFaction1`, `RewRepFaction2`, `RewRepFaction3`, `RewRepFaction4`, `RewRepFaction5`, `RewRepValueId1`, `RewRepValueId2`, `RewRepValueId3`, `RewRepValueId4`, `RewRepValueId5`, `RewRepValue1`, `RewRepValue2`, `RewRepValue3`, `RewRepValue4`, `RewRepValue5`, `RewHonorAddition`, `RewHonorMultiplier`, `unk0`, `RewOrReqMoney`, `RewMoneyMaxLevel`, `RewSpell`, `RewSpellCast`, `RewMailTemplateId`, `RewMailDelaySecs`, `PointMapId`, `PointX`, `PointY`, `PointOpt`, `DetailsEmote1`, `DetailsEmote2`, `DetailsEmote3`, `DetailsEmote4`, `DetailsEmoteDelay1`, `DetailsEmoteDelay2`, `DetailsEmoteDelay3`, `DetailsEmoteDelay4`, `IncompleteEmote`, `CompleteEmote`, `OfferRewardEmote1`, `OfferRewardEmote2`, `OfferRewardEmote3`, `OfferRewardEmote4`, `OfferRewardEmoteDelay1`, `OfferRewardEmoteDelay2`, `OfferRewardEmoteDelay3`, `OfferRewardEmoteDelay4`, `StartScript`, `CompleteScript`, `WDBVerified`)
VALUES
(11010, 2, 3522, -511, 70, 0, 70, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 128, 0, 0, 0, 0, 0, 0, 11023, 11010, 11023, 5, 32456, 1, 40197, 'Bomberangriff', 'Ihr habt ein fliegendes Reittier... ja und! Glaubt Ihr denn, dass Ihr das Zeug dazu habt, es gekonnt einzusetzen?$B$BDas Konstruktionslager: Wut und das Konstruktionslager: Terror, im Norden und im Süden, sind mir schon seit langem ein Dorn im Auge und obendrein bedrohen sie das friedliche Ogri\'la. Mit all diesen Teufelskanonen, die die Himmelswache von rechts und links unter Beschuss nehmen, gibt es einfach kein Hindurchkommen und unser Unterfangen ist zum Scheitern verurteilt.$B$BWürdet Ihr Euch gerne unter Beweis stellen? Nehmt diese Bomben und vernichtet ihre Munitionsvorräte. Lasst Euch aber nicht auch noch vom Himmel herunterholen!', 'Vernichtet mithilfe der Bomben der Himmelswache 15 Stapel mit Teufelskanonenkugeln.', 'Gut, gut, scheinbar seid Ihr doch härter im Nehmen als ich dachte. Ausgezeichnete Arbeit. Möglicherweise hatte der alte Keller doch Unrecht, was Euch anbelangt. <Himmelsoffizier Vanderlip grinst.>', 'Habt Ihr schon ihre Stapel mit Teufelskanonenkugeln vernichtet?', '', 'Kehrt zu Himmelsoffizier Vanderlip am Aussenposten der Himmelswache auf dem Schergrat zurück.', 'Stapel mit Teufelskanonenkugeln zerstört', 'Stapel mit Teufelskanonenkugeln zerstört', 'Stapel mit Teufelskanonenkugeln zerstört', '', 0, 32456, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 23118, 0, 0, 0, 15, 0, 0, 0, 40160, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1031, 1038, 0, 0, 0, 7, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 44000, 7500, 0, 40198, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 12340);



DELETE FROM `creature_questrelation` WHERE `quest` = 11102;
DELETE FROM `gameobject_questrelation` WHERE `quest` = 11102;
UPDATE `item_template` SET `StartQuest`=0 WHERE `StartQuest` = 11102;
INSERT INTO `creature_questrelation` (`id`, `quest`) VALUES (23120, 11102);
UPDATE `creature_template` SET `npcflag`=`npcflag`|2 WHERE `entry` = 23120;
DELETE FROM `creature_involvedrelation` WHERE `quest` = 11102;
DELETE FROM `gameobject_involvedrelation` WHERE `quest` = 11102;
INSERT INTO `creature_involvedrelation` (`id`, `quest`) VALUES (23120, 11102);
UPDATE `creature_template` SET `npcflag`=`npcflag`|2 WHERE `entry`=23120;
REPLACE INTO `quest_template` (`entry`, `Method`, `ZoneOrSort`, `SkillOrClassMask`, `MinLevel`, `MaxLevel`, `QuestLevel`, `Type`, `RequiredRaces`, `RequiredSkillValue`, `RepObjectiveFaction`, `RepObjectiveValue`, `RepObjectiveFaction2`, `RepObjectiveValue2`, `RequiredMinRepFaction`, `RequiredMinRepValue`, `RequiredMaxRepFaction`, `RequiredMaxRepValue`, `SuggestedPlayers`, `LimitTime`, `QuestFlags`, `SpecialFlags`, `CharTitleId`, `PlayersSlain`, `BonusTalents`, `RewardArenaPoints`, `PrevQuestId`, `NextQuestId`, `ExclusiveGroup`, `NextQuestInChain`, `RewXPId`, `SrcItemId`, `SrcItemCount`, `SrcSpell`, `Title`, `Details`, `Objectives`, `OfferRewardText`, `RequestItemsText`, `EndText`, `CompletedText`, `ObjectiveText1`, `ObjectiveText2`, `ObjectiveText3`, `ObjectiveText4`, `ReqItemId1`, `ReqItemId2`, `ReqItemId3`, `ReqItemId4`, `ReqItemId5`, `ReqItemId6`, `ReqItemCount1`, `ReqItemCount2`, `ReqItemCount3`, `ReqItemCount4`, `ReqItemCount5`, `ReqItemCount6`, `ReqSourceId1`, `ReqSourceId2`, `ReqSourceId3`, `ReqSourceId4`, `ReqSourceCount1`, `ReqSourceCount2`, `ReqSourceCount3`, `ReqSourceCount4`, `ReqCreatureOrGOId1`, `ReqCreatureOrGOId2`, `ReqCreatureOrGOId3`, `ReqCreatureOrGOId4`, `ReqCreatureOrGOCount1`, `ReqCreatureOrGOCount2`, `ReqCreatureOrGOCount3`, `ReqCreatureOrGOCount4`, `ReqSpellCast1`, `ReqSpellCast2`, `ReqSpellCast3`, `ReqSpellCast4`, `RewChoiceItemId1`, `RewChoiceItemId2`, `RewChoiceItemId3`, `RewChoiceItemId4`, `RewChoiceItemId5`, `RewChoiceItemId6`, `RewChoiceItemCount1`, `RewChoiceItemCount2`, `RewChoiceItemCount3`, `RewChoiceItemCount4`, `RewChoiceItemCount5`, `RewChoiceItemCount6`, `RewItemId1`, `RewItemId2`, `RewItemId3`, `RewItemId4`, `RewItemCount1`, `RewItemCount2`, `RewItemCount3`, `RewItemCount4`, `RewRepFaction1`, `RewRepFaction2`, `RewRepFaction3`, `RewRepFaction4`, `RewRepFaction5`, `RewRepValueId1`, `RewRepValueId2`, `RewRepValueId3`, `RewRepValueId4`, `RewRepValueId5`, `RewRepValue1`, `RewRepValue2`, `RewRepValue3`, `RewRepValue4`, `RewRepValue5`, `RewHonorAddition`, `RewHonorMultiplier`, `unk0`, `RewOrReqMoney`, `RewMoneyMaxLevel`, `RewSpell`, `RewSpellCast`, `RewMailTemplateId`, `RewMailDelaySecs`, `PointMapId`, `PointX`, `PointY`, `PointOpt`, `DetailsEmote1`, `DetailsEmote2`, `DetailsEmote3`, `DetailsEmote4`, `DetailsEmoteDelay1`, `DetailsEmoteDelay2`, `DetailsEmoteDelay3`, `DetailsEmoteDelay4`, `IncompleteEmote`, `CompleteEmote`, `OfferRewardEmote1`, `OfferRewardEmote2`, `OfferRewardEmote3`, `OfferRewardEmote4`, `OfferRewardEmoteDelay1`, `OfferRewardEmoteDelay2`, `OfferRewardEmoteDelay3`, `OfferRewardEmoteDelay4`, `StartScript`, `CompleteScript`, `WDBVerified`)
VALUES
(11102, 2, 3522, -1024, 70, 0, 70, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 128, 0, 0, 0, 0, 0, 0, 11023, 11010, 11023, 5, 32456, 1, 40197, 'Bomberangriff', 'Ihr könnt also wie eine Krähe herumfliegen... ja und! Schon mal etwas am Boden ausradiert, während Ihr geflogen seid? Lust, es mal zu probieren?$B$BDas Konstruktionslager: Wut und das Konstruktionslager: Terror, im Norden und im Süden, sind mir schon seit langem ein Dorn im Auge und eine Gefahr für Ogri\'la. Mit all diesen Teufelskanonen, die die Himmelswache von rechts und links unter Beschuss nimmt, gibt es einfach kein Hindurchkommen und unser Unterfangen ist zum Scheitern verurteilt.$B$BWürdet Ihr Euch gerne unter Beweis stellen? Nehmt diese Bomben und vernichtet ihre Munitionsvorräte. Lasst Euch aber nicht auch noch vom Himmel herunterholen!', 'Vernichtet mithilfe der Bomben der Himmelswache 15 Stapel mit Teufelskanonenkugeln.', 'Gut, gut, scheinbar seid Ihr doch härter im Nehmen als ich dachte. Ausgezeichnete Arbeit. Möglicherweise hatte der alte Keller doch Unrecht, was Euch anbelangt.$B$B<Himmelsoffizier Vanderlip grinst.>', 'Habt Ihr schon ihre Stapel mit Teufelskanonenkugeln vernichtet?', '', 'Kehrt zu Himmelsoffizier Vanderlip am Außenposten der Himmelswache auf dem Schergrat zurück.', 'Stapel mit Teufelskanonenkugeln zerstört', '', '', '', 0, 32456, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 23118, 0, 0, 0, 15, 0, 0, 0, 40160, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1031, 1038, 0, 0, 0, 7, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 44000, 7500, 0, 40198, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 12340);
